import requests
import json
import urllib3
urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)

TARGET_URL = "https://gstsandbox.charteredinfo.com/eicore/dec/v1.03/Invoice"
ASP_ID = "1805053626"
PASSWORD = "Bhavya2026@"
GSTIN = "34AACCC1596Q002"
USER_NAME = "TaxProEnvPON"
AUTH_TOKEN = "1oaWTqchgp6Tw6F09oEvUjyIq"

def test_api():
    headers = {
        "aspid": ASP_ID,
        "password": PASSWORD,
        "ip-usr": "127.0.0.1",
        "Gstin": GSTIN,
        "user_name": USER_NAME,
        "AuthToken": AUTH_TOKEN,
        "Content-Type": "application/json"
    }

    with open('payload.json', 'r') as f:
        payload_data = f.read()

    print(f"Sending JSON Payload generated by C#:")
    print("--------------------------------------------------")
    print(payload_data)
    print("--------------------------------------------------")

    print(f"Sending POST request to: {TARGET_URL}")
    response = requests.post(TARGET_URL, headers=headers, data=payload_data.strip(), verify=False)
    
    print(f"\nStatus Code: {response.status_code}")
    try:
        parsed = response.json()
        print(f"Response JSON:\n{json.dumps(parsed, indent=2)}")
    except:
        print(f"Response Text:\n{response.text}")

if __name__ == "__main__":
    test_api()
